doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: root, password: '1234', dbname: pimcore, mapping_types: { enum: string, bit: boolean }, server_version: 10.4.28-MariaDB } } }
